### ISSUE TITLE
problem with code at main.py line 126

### ISSUE THREAD

**Issue by XiaHua-Spark** [kuangliu/pytorch-cifar#1]
what does `net.module` mean?

**Comment by kuangliu** [comment]
If you use cuda, net is represented as `DataParallel`, `net.module` transforms `DataParallel` back to the ordinary `nn.Module`, which can be easily saved.

**Comment by XiaHua-Spark** [comment]
what if I don't have multi GPU support, how should I modify the code?

**Comment by kuangliu** [comment]
Change the `device_ids` to the GPU indices available.

**Comment by kuangliu** [comment]
I am close this issue for lack of response.
