### ISSUE TITLE
Pre-trained resnet50-101-152 models on Cifar 10 or 100

### ISSUE THREAD

**Issue by HaiPhan1991** [kuangliu/pytorch-cifar#11]
Hi Kuangliu,

Do you have an available pre-trained resnet (**50, 101, 152**) model (**weights, biases**) files on Cifar 10 or 100? I want to make some modifications to train on these datasets.
Thanks.

**Comment by kuangliu** [comment]
I don't provide pre-trained CIFAR10 ResNet models.
But you can download pre-trained ImageNet ResNet models from here:
https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
