### ISSUE TITLE
LeNet performance request

### ISSUE THREAD

**Issue by AruniRC** [kuangliu/pytorch-cifar#13]
Firstly, thank you for a comprehensive evaluation of all these models on CIFAR using PyTorch.

I noticed you have a LeNet network defined in your models, which is more-or-less identical to the one used in the PyTorch CIFAR example. Do you have the performance of this model on CIFAR-10?

It is a simple baseline, and I want to make sure my numbers are matching (getting only 65% test accuracy, which seems a bit suspicious).

**Comment by kuangliu** [comment]
I didn't train LeNet-5 on CIFAR10, I think 65% is reasonable. LeNet-5 is too simple, what you got is perfectly fine to me.
And VGG is a good model to start with.
