### ISSUE TITLE
Pre-activation ResNet

### ISSUE THREAD

**Issue by hengyuan-hu** [kuangliu/pytorch-cifar#15]
Line 134 may not be necessary if pre-activation is used. In the current implementation, if pre-activation is used, then there will be 2 consecutive BN layers after the first 3x3 conv
https://github.com/kuangliu/pytorch-cifar/blob/2ded13153236ab24252b3363ac412177fedcd833/models/resnet.py#L134

**Comment by kuangliu** [comment]
Yeah. Now I split pre-act-resnet out to a new file.
Thanks.
