### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by nor1take** [kuangliu/pytorch-cifar#157]
![image](https://user-images.githubusercontent.com/112241211/196704129-aa4c060d-d4c8-4887-9fd1-780f97ae4c2b.png)
Do anyone know how to solve this problem when running main.py?

**Comment by biyetianjian** [comment]
hello, i met the same problem as yours, could you tell me  how did you solve it? thank you very much

**Comment by nor1take** [comment]
@biyetianjian 
https://github.com/kuangliu/pytorch-cifar/issues/157#issuecomment-1512865071
this issue had already solved the problem.

**Comment by HuansongZhang** [comment]
import shutil
and change the error line to
 ''_, term_width = shutil.get_terminal_size()''
just follow other answer in this repo

**Comment by HuansongZhang** [comment]
> hello, i met the same problem as yours, could you tell me how did you solve it? thank you very much



> 

import shutil
and change the error line to
''_, term_width = shutil.get_terminal_size()''
just follow other answer in this repo
