### ISSUE TITLE
Why do you crop the data?

### ISSUE THREAD

**Issue by YandanYang** [kuangliu/pytorch-cifar#37]
While downloading and transform the dataset, I saw the command:
`transforms.RandomCrop(32, padding=4)`
But the original img is already 32*32, why do we need to crop？

**Comment by karandwivedi42** [comment]
The image is first padded to 36x36 (`padding=4`) and then cropped to 32x32. This is an input data augmentation (https://medium.com/nanonets/how-to-use-deep-learning-when-you-have-limited-data-part-2-data-augmentation-c26971dc8ced)

**Comment by YandanYang** [comment]
Thanks!
