### ISSUE TITLE
Issue about shortcut.

### ISSUE THREAD

**Issue by yunzhexue** [kuangliu/pytorch-cifar#4]
In your resnet model, you did a Relu activation before shortcut which after bn(conv2). I saw there are some other people just shortcut to the output of bn without Relu. Which one is better, did you try them separately before?

However, your work is great for new pytorcher like me ^_^. Hope to see wide resnet and deeplab in the future. 

Best wishes.

**Comment by kuangliu** [comment]
You are right. Shouldn't be a relu here. 
I think this is a typo, I checked this is no relu in the history version of this file. I'll remove it later. 
Thanks.
