### ISSUE TITLE
AttributeError: 'ResNet' object has no attribute 'to'

### ISSUE THREAD

**Issue by ggeh** [kuangliu/pytorch-cifar#40]
File "main.py", line 69, in <module>  net = net.to(device)
AttributeError: 'ResNet' object has no attribute 'to'

Is there anybody who got the same error?

**Comment by mario98** [comment]
Hint: Check your pytorch version, then carefully read current pytorch changelogs and see if you can spot any differences.

**Comment by kuangliu** [comment]
Use pytorch v0.4

**Comment by tejdeep94** [comment]
I tried with pytorch v0.4. Doesn't work. Same error shows up

**Comment by arieltci** [comment]
Same problem on version 0.3.0.post4, on google colab
