### ISSUE TITLE
'ResNet' object has no attribute 'to'

### ISSUE THREAD

**Issue by cuttrex** [kuangliu/pytorch-cifar#43]
Hi,
I'm totally a newbie in machine learning and I am trying out the transfer learning tutorial on the Pytorch website https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html. When I run the file, this error pops up : AttributeError: 'ResNet' object has no attribute 'to'. Can any help me?

**Comment by Vipermdl** [comment]
I have the same problem like you

**Comment by debadridtt** [comment]
For all models, it gives no attribute to.

**Comment by Vipermdl** [comment]
the function of 'to' haven't written. I write in another way. I also found some problem,for exemple, with torch.no_grad and so on.

**Comment by kuangliu** [comment]
Update pytorch to v0.4.

**Comment by willyzw1221** [comment]
'to' is a new api inpytorch 0.4.0.
so update pytorch.
