### ISSUE TITLE
Progress_bar value unpack error

### ISSUE THREAD

**Issue by debadridtt** [kuangliu/pytorch-cifar#44]
from utils import progress_bar
  File "C:\Users\Debadri\pytorch-cifar\utils.py", line 45, in <module>
    _, term_width = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)
I'm getting this error.
I'm writing this command:
"python main.py"

Is there any argument I need to pass?
![capture](https://user-images.githubusercontent.com/24243687/41277106-d92ae00c-6e43-11e8-836a-fb3d8bc73cfb.JPG)

**Comment by frozen86** [comment]
Because stty is a linux command, fail on windows.

**Comment by Ranchentx** [comment]
I met the same problem when I debug in ubuntu. It's ok when I run it in terminal. How to solve it?

**Comment by gmt710** [comment]
@debadridtt Have you solved the problem？

**Comment by kevin5k** [comment]
I encountered the same issue. the purpose of the getting the stty size is to get the terminal size. No idea why it is required. Anyway, I modified it to the following in Windows and my code compiled error-free:

`_, term_width = shutil.get_terminal_size()`

**Comment by debadridtt** [comment]
thanks will surely try this out. For now I'm closing the issue, if it doesn't workout, I'll reopen it again

**Comment by freyamehta99** [comment]
It still doesn't work on ubuntu. Please open this issue back

**Comment by GYee** [comment]
> I encountered the same issue. the purpose of the getting the stty size is to get the terminal size. No idea why it is required. Anyway, I modified it to the following in Windows and my code compiled error-free:
> 
> `_, term_width = shutil.get_terminal_size()`

it doesn't work

**Comment by ouening** [comment]
Just comment the line code `from utils import progress_bar`, and using `print` instead:

        print('Loss: %.3f | Acc: %.3f%% (%d/%d)'
            % (train_loss/(batch_idx+1), 100.*correct/total, correct, total))
        # progress_bar(batch_idx, len(trainloader), 'Loss: %.3f | Acc: %.3f%% (%d/%d)'
        #     % (train_loss/(batch_idx+1), 100.*correct/total, correct, total))

**Comment by chg0901** [comment]
> 
> 
> I encountered the same issue. the purpose of the getting the stty size is to get the terminal size. No idea why it is required. Anyway, I modified it to the following in Windows and my code compiled error-free:
> 
> `_, term_width = shutil.get_terminal_size()`

@kevin5k  Could you please show us what's the shutil?

**Comment by chg0901** [comment]
> 
> 
> > I encountered the same issue. the purpose of the getting the stty size is to get the terminal size. No idea why it is required. Anyway, I modified it to the following in Windows and my code compiled error-free:
> > `_, term_width = shutil.get_terminal_size()`
> 
> it doesn't work

@GYee  You can reference my reply at [link](https://github.com/kuangliu/pytorch-cifar/issues/44#issuecomment-566417243)
