### ISSUE TITLE
What does the 1x1 average pooling layer do in VGG models?

### ISSUE THREAD

**Issue by JC-S** [kuangliu/pytorch-cifar#47]
In this line:
https://github.com/kuangliu/pytorch-cifar/blob/master/models/vgg.py#L37
There is a 1x1 average pooling layer with stride 1. According to my knowledge of pooling, this layer basically does nothing?

**Comment by myhub** [comment]
Why there is no answer?

**Comment by dongliangchang** [comment]
BD
