### ISSUE TITLE
small mistake(?) at the inception class code

### ISSUE THREAD

**Issue by chahrazaddo** [kuangliu/pytorch-cifar#5]
hello @kuangliu , i would like to thank you for your work :+1:  there is a small mistake i guess in the GoogleNet model, the inception class, you added one more conv2d in the 5x5 branch, it shouldn't only be one 1x1 conv followed by one 5x5 conv and not two ?

**Comment by kuangliu** [comment]
You are right.
I split the 5x5 conv into two 3x3 conv, I prefer to use smaller kernels.
