### ISSUE TITLE
The problem of  No such file or directory: './checkpoint/ckpt.t7'

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [kuangliu/pytorch-cifar#63]
how to solve this problem? can anyone help me ?

**Comment by cadurosar** [comment]
You have to run mkdir checkpoint to ensure that the checkpoint folder exists

**Comment by Bearsuny** [comment]
May be you used this command `python main.py --resume --lr=0.01`, if you use the argument `--resume`, it will find the checkpoint dir and checkpoint file. So, for the first time, you may use `python main.py --lr=0.01`. If you want resume from the past training model, you could add the `--resume` argument, and it will continue the checkpoint which the checkpoint file refer to.

**Comment by Ixiaohuihuihui** [comment]
I got it，thank you very much!
